window.ONYX_TOKENS = [
  {
    id: "100",
    name: "ONE Hundred",
    symbol: "ONE",
    issuer: "roneGNc3hdSwWZEr54RZceQr8Fftq6fkL",
    totalSupply: 100,
    renderLimit: 100,
    cacheTtlSec: 120,
    useIssuerAvatar: false,
    logoUrl: "./emoji-100-gold.svg",
    logoRounded: false,
    excludeIssuer: false,
    excludedAddresses: [],
    logo: "100",
    theme: "genesis",
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/roneGNc3hdSwWZEr54RZceQr8Fftq6fkL/ONE",
    xUrl: "https://x.com/One_Xahau",
    description:
      "A tiny-supply culture token built to make you touch the DEX. Genesis of Onyx drops: hold 1+ and you're in the future set.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "genesis", title: "Genesis Member", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 1, rule: "Hold >= 1 {symbol}" },
      { id: "whale", title: "Whale", icon: "\u{1F40B}", className: "club", type: "threshold", min: 5, rule: "Hold >= 5 {symbol}" },
      { id: "council", title: "Council", icon: "\u{1F5A4}", className: "dark", type: "threshold", min: 10, rule: "Hold >= 10 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10],
  },
  {
    id: "evr",
    name: "Evers",
    symbol: "EVR",
    issuer: "rEvernodee8dJLaFsujS6q1EiXvZYmHXr8",
    totalSupply: 72253440,
    renderLimit: 100,
    cacheTtlSec: 120,
    excludeIssuer: false,
    excludedAddresses: [],
    logo: "EVR",
    theme: "evernode",
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/rEvernodee8dJLaFsujS6q1EiXvZYmHXr8/EVR",
    xUrl: "https://x.com/EvernodeXRPL",
    description:
      "Evernode's native token on Xahau, used for hosting, registration, and dApp service payments.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "starter", title: "Starter", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 100, rule: "Hold >= 100 {symbol}" },
      { id: "builder", title: "Builder", icon: "\u{1F535}", className: "education", type: "threshold", min: 1000, rule: "Hold >= 1000 {symbol}" },
      { id: "operator", title: "Operator", icon: "\u{1F7E3}", className: "dark", type: "threshold", min: 10000, rule: "Hold >= 10000 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10],
  },
  {
    id: "xmerch",
    name: "Xmerch",
    symbol: "XMERCH",
    currency: "584D455243480000000000000000000000000000",
    issuer: "rLRVSaK575YXwwnkC5QSTLK7E1r1ps5TCs",
    totalSupply: 100000000,
    renderLimit: 100,
    cacheTtlSec: 120,
    excludeIssuer: false,
    excludedAddresses: [],
    logo: "XM",
    theme: "xmerch",
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/rLRVSaK575YXwwnkC5QSTLK7E1r1ps5TCs/584D455243480000000000000000000000000000",
    xUrl: "https://x.com/xMerch_",
    description:
      "Xmerch token on Xahau used across the xMerch ecosystem.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "starter", title: "Starter", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 100, rule: "Hold >= 100 {symbol}" },
      { id: "builder", title: "Builder", icon: "\u{1F535}", className: "education", type: "threshold", min: 1000, rule: "Hold >= 1000 {symbol}" },
      { id: "operator", title: "Operator", icon: "\u{1F7E3}", className: "dark", type: "threshold", min: 10000, rule: "Hold >= 10000 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10],
  },
];

