window.ONYX_DEFAULT_TOKEN_ID = "xah";

window.ONYX_TOKENS = [
  {
    id: "xah",
    name: "Xahau",
    symbol: "XAH",
    nativeXah: true,
    issuer: "",
    currency: "XAH",
    totalSupply: 0,
    renderLimit: 100,
    cacheTtlSec: 1800,
    excludeIssuer: false,
    excludedAddresses: [
      "rBiGVAULtVEc2yMnop587w5pgiZ7EWAyUj",
      "rLockEDUP1tGp3cEfajBZ9R4hCg346Bsp6",
      "rK2y8aaRdEFpr2GUrqs1iuTCUsWgS5mHHW"
    ],
    logoUrl: "https://raw.githubusercontent.com/Xahau/Graphics/main/xahau-icon-yellow.svg",
    logoRounded: false,
    logo: "XAH",
    theme: "xahau",
    liquidityProfile: "commercial", // options: commercial | alt
    liquidityScoreScale: "A", // options: A (balanced) | B (depth-first)
    liquidityDepthTargetUsd: 10000,
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com",
    xUrl: "https://x.com/XahauNetwork",
    xahImportUrl: "https://xumm.app/detect/xapp:nixer.xahauimport",
    bitrueTradeUrl: "https://www.bitrue.com/trade/xah_usdt",
    xahTeleportUrl: "https://xumm.app/detect/xapp:xahau.teleport",
    whitepaper: "XAH is the native asset of the Xahau network. This view tracks USD pricing and market context.",
    whitepaperHtml: "https://xahau.org/docs/resources/whitepaper",
    description:
      "Native network asset on Xahau, priced directly in USD for this dashboard.",
    badgeRules: [],
    whaleTopN: [1, 3, 5, 10, 25, 50],
  },
  {
    id: "100",
    name: "ONE Hundred",
    symbol: "ONE",
    issuer: "roneGNc3hdSwWZEr54RZceQr8Fftq6fkL",
    totalSupply: 100,
    renderLimit: 100,
    cacheTtlSec: 120,
    useIssuerAvatar: false,
    logoUrl: "./emoji-100-gold.svg",
    logoRounded: false,
    excludeIssuer: false,
    excludedAddresses: [],
    logo: "100",
    theme: "genesis",
    liquidityProfile: "alt",
    liquidityScoreScale: "A",
    liquidityDepthTargetUsd: 500,
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/roneGNc3hdSwWZEr54RZceQr8Fftq6fkL/ONE",
    xUrl: "https://x.com/One_Xahau",
    whitepaper: "ONE is a tiny-supply culture token on Xahau. Core thesis: social coordination through scarce supply, transparent holder distribution, and live DEX participation.",
    whitepaperHtml: "",
    description:
      "A tiny-supply culture token built to make you touch the DEX. Genesis of Onyx drops: hold 1+ and you're in the future set.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "genesis", title: "Genesis Member", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 1, rule: "Hold >= 1 {symbol}" },
      { id: "whale", title: "Whale", icon: "\u{1F40B}", className: "club", type: "threshold", min: 5, rule: "Hold >= 5 {symbol}" },
      { id: "council", title: "Council", icon: "\u{1F5A4}", className: "dark", type: "threshold", min: 10, rule: "Hold >= 10 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10, 25, 50],
  },
  {
    id: "evr",
    name: "Evers",
    symbol: "EVR",
    issuer: "rEvernodee8dJLaFsujS6q1EiXvZYmHXr8",
    totalSupply: 72253440,
    renderLimit: 100,
    cacheTtlSec: 120,
    excludeIssuer: false,
    excludedAddresses: ["rHktfGUbjqzU4GsYCMc1pDjdHXb5CJamto","ra9g3LAJm9xJu8Awe7oWzR6VXFB1mpFtSe","rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH"],
    logo: "EVR",
    theme: "evernode",
    liquidityProfile: "alt",
    liquidityScoreScale: "A",
    liquidityDepthTargetUsd: 500,
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/rEvernodee8dJLaFsujS6q1EiXvZYmHXr8/EVR",
    xUrl: "https://x.com/EvernodeXRPL",
    whitepaper: "EVR is Evernode's utility token on Xahau, used in host economics and service coordination. Holder concentration and activity metrics are shown here for transparency.",
    whitepaperHtml: "https://raw.githubusercontent.com/EvernodeXRPL/whitepaper/main/Evernode%202.0.pdf",
    description:
      "Evernode's native token on Xahau, used for hosting, registration, and dApp service payments.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "starter", title: "Starter", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 100, rule: "Hold >= 100 {symbol}" },
      { id: "builder", title: "Builder", icon: "\u{1F535}", className: "education", type: "threshold", min: 1000, rule: "Hold >= 1000 {symbol}" },
      { id: "operator", title: "Operator", icon: "\u{1F7E3}", className: "dark", type: "threshold", min: 10000, rule: "Hold >= 10000 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10, 25, 50],
  },
  {
    id: "xmerch",
    name: "Xmerch",
    symbol: "XMERCH",
    currency: "584D455243480000000000000000000000000000",
    issuer: "rLRVSaK575YXwwnkC5QSTLK7E1r1ps5TCs",
    totalSupply: 100000000,
    renderLimit: 100,
    cacheTtlSec: 120,
    excludeIssuer: false,
    excludedAddresses: [],
    logo: "XM",
    theme: "xmerch",
    liquidityProfile: "alt",
    liquidityScoreScale: "A",
    liquidityDepthTargetUsd: 500,
    ws: "wss://xahau.network",
    explorerUrl: "https://xahauexplorer.com/en/token/rLRVSaK575YXwwnkC5QSTLK7E1r1ps5TCs/584D455243480000000000000000000000000000",
    xUrl: "https://x.com/xMerch_",
    whitepaper: "XMERCH is an ecosystem token for xMerch activity on Xahau. This hub tracks distribution, holder badges, and live trustline-driven activity to monitor adoption.",
    whitepaperHtml: "https://www.xmerch.app/",
    description:
      "Xmerch token on Xahau used across the xMerch ecosystem.",
    badgeRules: [
      { id: "top1", title: "Top Holder", icon: "\u{1F947}", className: "gold", type: "rank", rank: 1, rule: "Rank #1 wallet" },
      { id: "top2", title: "Runner Up", icon: "\u{1F948}", className: "silver", type: "rank", rank: 2, rule: "Rank #2 wallet" },
      { id: "top3", title: "Third Place", icon: "\u{1F949}", className: "bronze", type: "rank", rank: 3, rule: "Rank #3 wallet" },
      { id: "last", title: "Last Holder", icon: "\u2764\uFE0F", className: "red", type: "last", rule: "Hold the last rank" },
      { id: "starter", title: "Starter", icon: "\u{1F7E2}", className: "club", type: "threshold", min: 100, rule: "Hold >= 100 {symbol}" },
      { id: "builder", title: "Builder", icon: "\u{1F535}", className: "education", type: "threshold", min: 1000, rule: "Hold >= 1000 {symbol}" },
      { id: "operator", title: "Operator", icon: "\u{1F7E3}", className: "dark", type: "threshold", min: 10000, rule: "Hold >= 10000 {symbol}" },
      { id: "dex", title: "DEX Culture", icon: "\u{1F535}", className: "education", type: "any", rule: "Hold any amount (> 0)" },
      { id: "exact1", title: "Exact One", icon: "\u{1F3AF}", className: "club", type: "exact", value: 1, epsilon: 0.000000001, rule: "Hold exactly 1.0000" },
    ],
    whaleTopN: [1, 3, 5, 10, 25, 50],
  },
];

